//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDescuelaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumno
    {
        public int mat_alu { get; set; }
        public string nom_alu { get; set; }
        public Nullable<int> edad_alu { get; set; }
        public Nullable<int> sem_alu { get; set; }
        public string gen_alu { get; set; }
        public Nullable<int> clave_c1 { get; set; }
    
        public virtual carrera carrera { get; set; }
    }
}
