//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDescuelaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class materia
    {
        public int clave_m { get; set; }
        public string nom_m { get; set; }
        public Nullable<double> cred_m { get; set; }
    }
}
